/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It is kept in sync with the file routes in this project.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AccessRouteImport } from './routes/access'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as IndexRouteImport } from './routes/index'

const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/integrations': typeof IntegrationsRoute
  '/registry': typeof RegistryRoute
  '/registration': typeof RegistrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/integrations': typeof IntegrationsRoute
  '/registry': typeof RegistryRoute
  '/registration': typeof RegistrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/integrations': typeof IntegrationsRoute
  '/registry': typeof RegistryRoute
  '/registration': typeof RegistrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/access' | '/ai' | '/analytics' | '/integrations' | '/registry' | '/registration'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/access' | '/ai' | '/analytics' | '/integrations' | '/registry' | '/registration'
  id: '__root__' | '/' | '/access' | '/ai' | '/analytics' | '/integrations' | '/registry' | '/registration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  RegistryRoute: typeof RegistryRoute
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  IntegrationsRoute: IntegrationsRoute,
  RegistryRoute: RegistryRoute,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
